repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.1
  hooks:
   - id: nbqa-black
     additional_dependencies: [black==20.8b1]
   - id: nbqa-pyupgrade
     additional_dependencies: [pyupgrade==2.7.3]
     args: [--py311-plus]
   - id: nbqa-isort
     args: [--profile=black]
     additional_dependencies: [isort==5.6.4]
  - id: nbqa-flake8
    additional_dependencies: [flake8==3.8.4]
  - id: nbqa-blacken-docs
    args: [--nbqa-md --nbqa-diff]
    additional_dependencies: [blacken-docs==1.16.0]
  - id: nbqa-pydocstyle
  - id: nbqa-pylint
