repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.1
  hooks:
    - id: nbqa-black
      additional_dependencies: [black==24.1.1]
    - id: nbqa-pyupgrade
      additional_dependencies: [pyupgrade==2.7.3]
      args: [--py38-plus]
    - id: nbqa-isort
      args: [--profile=black]
      additional_dependencies: [isort==5.6.4]
    # - id: nbqa-flake8
    #   additional_dependencies: [flake8==3.8.4]
    # - id: nbqa-pydocstyle
- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
    - id: nbstripout
- repo: https://github.com/asottile/blacken-docs
  rev: 1.16.0
  hooks:
    - id: blacken-docs
